---
  
- hosts: all
  vars:
    ansible_host_key_checking: false
  become: yes

  tasks:

   - name: ensure apt list dir exists
      file:
      path: /var/lib/apt/lists/
      state: directory
      mode: 0755

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes